---
new_page_extension: md
auto_deploy: false
admin_path: public/static/admin
webhook_url: 
sections:
- type: document
  path: public/static/content/index.md
  label: Inicio
  templates:
  - index
- type: document
  path: public/static/content/laboratorio.md
  label: laboratorio
  templates:
  - index
upload_dir: ''
public_path: https://nemiliz.s3-us-west-2.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
